### ISSUE TITLE
read pair UMI formation

### ISSUE THREAD

**Issue by lheisler** [oicr-gsi/barcodex#24]
UMI are extracted from read pairs.  for the current library we are working with UMI are either 3 or 4 bases.  These are concatenated into a single string of 6-8 bases.

This makes it difficult to determine the individual umi that makes up this pair.
is there any reason why they cannot be concatenated with a separator?
ie
AGTCCGC -> AGTC.CGC

**Comment by rjovelin** [comment]
Do we need to keep track of the origin of each UMI in the concatenated sequence?
debarcer, and to my knowledge umitools, do not  handle  AGTC.CGC. Each tool concatenate the sequences before annotating the read name

**Comment by lheisler** [comment]
I think it would be good to have this, especially for these cases where the UMI are of variable length.  I can see us going back to this umi-extracted data and wanting to assess in more detail.

If it will break the downstream tools, then it can't really go into the fastq files.

**Comment by rjovelin** [comment]
The origin of the UMIs can already be obtained from the fastqs with extracted sequences using the regex or pattern used for extraction, or a modified regex that includes only the discarded and umi parts. 

Modifying the json with UMI counts from each read
